// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPBJjByvMNR2DoGwtXUYHDQnGh4J5gP8',
    appId: '1:430615036279:web:c124941e308d43d0942172',
    messagingSenderId: '430615036279',
    projectId: 'animeishi-73560',
    authDomain: 'animeishi-73560.firebaseapp.com',
    storageBucket: 'animeishi-73560.firebasestorage.app',
    measurementId: 'G-X3XNY74Z4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHm14k2b7f6CoFB3SEKvwp-WqUkVglisk',
    appId: '1:430615036279:android:d4564b3b6e1e7d58942172',
    messagingSenderId: '430615036279',
    projectId: 'animeishi-73560',
    storageBucket: 'animeishi-73560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWWzFEqLaYbzHc9ePMePS2hQYAQmJJVA0',
    appId: '1:430615036279:ios:de88a8a99de6ef63942172',
    messagingSenderId: '430615036279',
    projectId: 'animeishi-73560',
    storageBucket: 'animeishi-73560.firebasestorage.app',
    iosBundleId: 'com.example.animeishi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWWzFEqLaYbzHc9ePMePS2hQYAQmJJVA0',
    appId: '1:430615036279:ios:de88a8a99de6ef63942172',
    messagingSenderId: '430615036279',
    projectId: 'animeishi-73560',
    storageBucket: 'animeishi-73560.firebasestorage.app',
    iosBundleId: 'com.example.animeishi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPBJjByvMNR2DoGwtXUYHDQnGh4J5gP8',
    appId: '1:430615036279:web:2cc8b888a54a437f942172',
    messagingSenderId: '430615036279',
    projectId: 'animeishi-73560',
    authDomain: 'animeishi-73560.firebaseapp.com',
    storageBucket: 'animeishi-73560.firebasestorage.app',
    measurementId: 'G-D36HJDVY12',
  );

}